import _ from 'lodash'

export const friendOptions = [
  {
    key: 'Jenny Hess',
    text: 'Jenny Hess',
    value: 'Jenny Hess',
    image: { avatar: true, src: '/images/avatar/small/jenny.jpg' },
  },
  {
    key: 'Elliot Fu',
    text: 'Elliot Fu',
    value: 'Elliot Fu',
    image: { avatar: true, src: '/images/avatar/small/elliot.jpg' },
  },
  {
    key: 'Stevie Feliciano',
    text: 'Stevie Feliciano',
    value: 'Stevie Feliciano',
    image: { avatar: true, src: '/images/avatar/small/stevie.jpg' },
  },
  {
    key: 'Christian',
    text: 'Christian',
    value: 'Christian',
    image: { avatar: true, src: '/images/avatar/small/christian.jpg' },
  },
  {
    key: 'Matt',
    text: 'Matt',
    value: 'Matt',
    image: { avatar: true, src: '/images/avatar/small/matt.jpg' },
  },
  {
    key: 'Justen Kitsune',
    text: 'Justen Kitsune',
    value: 'Justen Kitsune',
    image: { avatar: true, src: '/images/avatar/small/justen.jpg' },
  },
]

export const countryOptions = [
  { code: 0, key: 'af', value: 'af', flag: 'af', text: 'Afghanistan' },
  { code: 1, key: 'ax', value: 'ax', flag: 'ax', text: 'Aland Islands' },
  { code: 2, key: 'al', value: 'al', flag: 'al', text: 'Albania' },
  { code: 3, key: 'dz', value: 'dz', flag: 'dz', text: 'Algeria' },
  { code: 4, key: 'as', value: 'as', flag: 'as', text: 'American Samoa' },
  { code: 5, key: 'ad', value: 'ad', flag: 'ad', text: 'Andorra' },
  { code: 6, key: 'ao', value: 'ao', flag: 'ao', text: 'Angola' },
  { code: 7, key: 'ai', value: 'ai', flag: 'ai', text: 'Anguilla' },
  { code: 8, key: 'ag', value: 'ag', flag: 'ag', text: 'Antigua' },
  { code: 9, key: 'ar', value: 'ar', flag: 'ar', text: 'Argentina' },
  { code: 10, key: 'am', value: 'am', flag: 'am', text: 'Armenia' },
  { code: 11, key: 'aw', value: 'aw', flag: 'aw', text: 'Aruba' },
  { code: 12, key: 'au', value: 'au', flag: 'au', text: 'Australia' },
  { code: 13, key: 'at', value: 'at', flag: 'at', text: 'Austria' },
  { code: 14, key: 'az', value: 'az', flag: 'az', text: 'Azerbaijan' },
  { code: 15, key: 'bs', value: 'bs', flag: 'bs', text: 'Bahamas' },
  { code: 16, key: 'bh', value: 'bh', flag: 'bh', text: 'Bahrain' },
  { code: 17, key: 'bd', value: 'bd', flag: 'bd', text: 'Bangladesh' },
  { code: 18, key: 'bb', value: 'bb', flag: 'bb', text: 'Barbados' },
  { code: 19, key: 'by', value: 'by', flag: 'by', text: 'Belarus' },
  { code: 20, key: 'be', value: 'be', flag: 'be', text: 'Belgium' },
  { code: 21, key: 'bz', value: 'bz', flag: 'bz', text: 'Belize' },
  { code: 22, key: 'bj', value: 'bj', flag: 'bj', text: 'Benin' },
  { code: 23, key: 'bm', value: 'bm', flag: 'bm', text: 'Bermuda' },
  { code: 24, key: 'bt', value: 'bt', flag: 'bt', text: 'Bhutan' },
  { code: 25, key: 'bo', value: 'bo', flag: 'bo', text: 'Bolivia' },
  { code: 26, key: 'ba', value: 'ba', flag: 'ba', text: 'Bosnia' },
  { code: 27, key: 'bw', value: 'bw', flag: 'bw', text: 'Botswana' },
  { code: 28, key: 'bv', value: 'bv', flag: 'bv', text: 'Bouvet Island' },
  { code: 29, key: 'br', value: 'br', flag: 'br', text: 'Brazil' },
  { code: 30, key: 'vg', value: 'vg', flag: 'vg', text: 'British Virgin Islands' },
  { code: 31, key: 'bn', value: 'bn', flag: 'bn', text: 'Brunei' },
  { code: 32, key: 'bg', value: 'bg', flag: 'bg', text: 'Bulgaria' },
  { code: 33, key: 'bf', value: 'bf', flag: 'bf', text: 'Burkina Faso' },
  { code: 34, key: 'bi', value: 'bi', flag: 'bi', text: 'Burundi' },
  { code: 35, key: 'tc', value: 'tc', flag: 'tc', text: 'Caicos Islands' },
  { code: 36, key: 'kh', value: 'kh', flag: 'kh', text: 'Cambodia' },
  { code: 37, key: 'cm', value: 'cm', flag: 'cm', text: 'Cameroon' },
  { code: 38, key: 'ca', value: 'ca', flag: 'ca', text: 'Canada' },
  { code: 39, key: 'cv', value: 'cv', flag: 'cv', text: 'Cape Verde' },
  { code: 40, key: 'ky', value: 'ky', flag: 'ky', text: 'Cayman Islands' },
  { code: 41, key: 'cf', value: 'cf', flag: 'cf', text: 'Central African Republic' },
  { code: 42, key: 'td', value: 'td', flag: 'td', text: 'Chad' },
  { code: 43, key: 'cl', value: 'cl', flag: 'cl', text: 'Chile' },
  { code: 44, key: 'cn', value: 'cn', flag: 'cn', text: 'China' },
  { code: 45, key: 'cx', value: 'cx', flag: 'cx', text: 'Christmas Island' },
  { code: 46, key: 'cc', value: 'cc', flag: 'cc', text: 'Cocos Islands' },
  { code: 47, key: 'co', value: 'co', flag: 'co', text: 'Colombia' },
  { code: 48, key: 'km', value: 'km', flag: 'km', text: 'Comoros' },
  { code: 49, key: 'cg', value: 'cg', flag: 'cg', text: 'Congo Brazzaville' },
  { code: 50, key: 'cd', value: 'cd', flag: 'cd', text: 'Congo' },
  { code: 51, key: 'ck', value: 'ck', flag: 'ck', text: 'Cook Islands' },
  { code: 52, key: 'cr', value: 'cr', flag: 'cr', text: 'Costa Rica' },
  { code: 53, key: 'ci', value: 'ci', flag: 'ci', text: 'Cote Divoire' },
  { code: 54, key: 'hr', value: 'hr', flag: 'hr', text: 'Croatia' },
  { code: 55, key: 'cu', value: 'cu', flag: 'cu', text: 'Cuba' },
  { code: 56, key: 'cy', value: 'cy', flag: 'cy', text: 'Cyprus' },
  { code: 57, key: 'cz', value: 'cz', flag: 'cz', text: 'Czech Republic' },
  { code: 58, key: 'dk', value: 'dk', flag: 'dk', text: 'Denmark' },
  { code: 59, key: 'dj', value: 'dj', flag: 'dj', text: 'Djibouti' },
  { code: 60, key: 'dm', value: 'dm', flag: 'dm', text: 'Dominica' },
  { code: 61, key: 'do', value: 'do', flag: 'do', text: 'Dominican Republic' },
  { code: 62, key: 'ec', value: 'ec', flag: 'ec', text: 'Ecuador' },
  { code: 63, key: 'eg', value: 'eg', flag: 'eg', text: 'Egypt' },
  { code: 64, key: 'sv', value: 'sv', flag: 'sv', text: 'El Salvador' },
  { code: 65, key: 'gb', value: 'gb', flag: 'gb', text: 'England' },
  { code: 66, key: 'gq', value: 'gq', flag: 'gq', text: 'Equatorial Guinea' },
  { code: 67, key: 'er', value: 'er', flag: 'er', text: 'Eritrea' },
  { code: 68, key: 'ee', value: 'ee', flag: 'ee', text: 'Estonia' },
  { code: 69, key: 'et', value: 'et', flag: 'et', text: 'Ethiopia' },
  { code: 70, key: 'eu', value: 'eu', flag: 'eu', text: 'European Union' },
  { code: 71, key: 'fk', value: 'fk', flag: 'fk', text: 'Falkland Islands' },
  { code: 72, key: 'fo', value: 'fo', flag: 'fo', text: 'Faroe Islands' },
  { code: 73, key: 'fj', value: 'fj', flag: 'fj', text: 'Fiji' },
  { code: 74, key: 'fi', value: 'fi', flag: 'fi', text: 'Finland' },
  { code: 75, key: 'fr', value: 'fr', flag: 'fr', text: 'France' },
  { code: 76, key: 'gf', value: 'gf', flag: 'gf', text: 'French Guiana' },
  { code: 77, key: 'pf', value: 'pf', flag: 'pf', text: 'French Polynesia' },
  { code: 78, key: 'tf', value: 'tf', flag: 'tf', text: 'French Territories' },
  { code: 79, key: 'ga', value: 'ga', flag: 'ga', text: 'Gabon' },
  { code: 80, key: 'gm', value: 'gm', flag: 'gm', text: 'Gambia' },
  { code: 81, key: 'ge', value: 'ge', flag: 'ge', text: 'Georgia' },
  { code: 82, key: 'de', value: 'de', flag: 'de', text: 'Germany' },
  { code: 83, key: 'gh', value: 'gh', flag: 'gh', text: 'Ghana' },
  { code: 84, key: 'gi', value: 'gi', flag: 'gi', text: 'Gibraltar' },
  { code: 85, key: 'gr', value: 'gr', flag: 'gr', text: 'Greece' },
  { code: 86, key: 'gl', value: 'gl', flag: 'gl', text: 'Greenland' },
  { code: 87, key: 'gd', value: 'gd', flag: 'gd', text: 'Grenada' },
  { code: 88, key: 'gp', value: 'gp', flag: 'gp', text: 'Guadeloupe' },
  { code: 89, key: 'gu', value: 'gu', flag: 'gu', text: 'Guam' },
  { code: 90, key: 'gt', value: 'gt', flag: 'gt', text: 'Guatemala' },
  { code: 91, key: 'gw', value: 'gw', flag: 'gw', text: 'Guinea-Bissau' },
  { code: 92, key: 'gn', value: 'gn', flag: 'gn', text: 'Guinea' },
  { code: 93, key: 'gy', value: 'gy', flag: 'gy', text: 'Guyana' },
  { code: 94, key: 'ht', value: 'ht', flag: 'ht', text: 'Haiti' },
  { code: 95, key: 'hm', value: 'hm', flag: 'hm', text: 'Heard Island' },
  { code: 96, key: 'hn', value: 'hn', flag: 'hn', text: 'Honduras' },
  { code: 97, key: 'hk', value: 'hk', flag: 'hk', text: 'Hong Kong' },
  { code: 98, key: 'hu', value: 'hu', flag: 'hu', text: 'Hungary' },
  { code: 99, key: 'is', value: 'is', flag: 'is', text: 'Iceland' },
  { code: 100, key: 'in', value: 'in', flag: 'in', text: 'India' },
  { code: 101, key: 'io', value: 'io', flag: 'io', text: 'Indian Ocean Territory' },
  { code: 102, key: 'id', value: 'id', flag: 'id', text: 'Indonesia' },
  { code: 103, key: 'ir', value: 'ir', flag: 'ir', text: 'Iran' },
  { code: 104, key: 'iq', value: 'iq', flag: 'iq', text: 'Iraq' },
  { code: 105, key: 'ie', value: 'ie', flag: 'ie', text: 'Ireland' },
  { code: 106, key: 'il', value: 'il', flag: 'il', text: 'Israel' },
  { code: 107, key: 'it', value: 'it', flag: 'it', text: 'Italy' },
  { code: 108, key: 'jm', value: 'jm', flag: 'jm', text: 'Jamaica' },
  { code: 109, key: 'jp', value: 'jp', flag: 'jp', text: 'Japan' },
  { code: 110, key: 'jo', value: 'jo', flag: 'jo', text: 'Jordan' },
  { code: 111, key: 'kz', value: 'kz', flag: 'kz', text: 'Kazakhstan' },
  { code: 112, key: 'ke', value: 'ke', flag: 'ke', text: 'Kenya' },
  { code: 113, key: 'ki', value: 'ki', flag: 'ki', text: 'Kiribati' },
  { code: 114, key: 'kw', value: 'kw', flag: 'kw', text: 'Kuwait' },
  { code: 115, key: 'kg', value: 'kg', flag: 'kg', text: 'Kyrgyzstan' },
  { code: 116, key: 'la', value: 'la', flag: 'la', text: 'Laos' },
  { code: 117, key: 'lv', value: 'lv', flag: 'lv', text: 'Latvia' },
  { code: 118, key: 'lb', value: 'lb', flag: 'lb', text: 'Lebanon' },
  { code: 119, key: 'ls', value: 'ls', flag: 'ls', text: 'Lesotho' },
  { code: 120, key: 'lr', value: 'lr', flag: 'lr', text: 'Liberia' },
  { code: 121, key: 'ly', value: 'ly', flag: 'ly', text: 'Libya' },
  { code: 122, key: 'li', value: 'li', flag: 'li', text: 'Liechtenstein' },
  { code: 123, key: 'lt', value: 'lt', flag: 'lt', text: 'Lithuania' },
  { code: 124, key: 'lu', value: 'lu', flag: 'lu', text: 'Luxembourg' },
  { code: 125, key: 'mo', value: 'mo', flag: 'mo', text: 'Macau' },
  { code: 126, key: 'mk', value: 'mk', flag: 'mk', text: 'Macedonia' },
  { code: 127, key: 'mg', value: 'mg', flag: 'mg', text: 'Madagascar' },
  { code: 128, key: 'mw', value: 'mw', flag: 'mw', text: 'Malawi' },
  { code: 129, key: 'my', value: 'my', flag: 'my', text: 'Malaysia' },
  { code: 130, key: 'mv', value: 'mv', flag: 'mv', text: 'Maldives' },
  { code: 131, key: 'ml', value: 'ml', flag: 'ml', text: 'Mali' },
  { code: 132, key: 'mt', value: 'mt', flag: 'mt', text: 'Malta' },
  { code: 133, key: 'mh', value: 'mh', flag: 'mh', text: 'Marshall Islands' },
  { code: 134, key: 'mq', value: 'mq', flag: 'mq', text: 'Martinique' },
  { code: 135, key: 'mr', value: 'mr', flag: 'mr', text: 'Mauritania' },
  { code: 136, key: 'mu', value: 'mu', flag: 'mu', text: 'Mauritius' },
  { code: 137, key: 'yt', value: 'yt', flag: 'yt', text: 'Mayotte' },
  { code: 138, key: 'mx', value: 'mx', flag: 'mx', text: 'Mexico' },
  { code: 139, key: 'fm', value: 'fm', flag: 'fm', text: 'Micronesia' },
  { code: 140, key: 'md', value: 'md', flag: 'md', text: 'Moldova' },
  { code: 141, key: 'mc', value: 'mc', flag: 'mc', text: 'Monaco' },
  { code: 142, key: 'mn', value: 'mn', flag: 'mn', text: 'Mongolia' },
  { code: 143, key: 'me', value: 'me', flag: 'me', text: 'Montenegro' },
  { code: 144, key: 'ms', value: 'ms', flag: 'ms', text: 'Montserrat' },
  { code: 145, key: 'ma', value: 'ma', flag: 'ma', text: 'Morocco' },
  { code: 146, key: 'mz', value: 'mz', flag: 'mz', text: 'Mozambique' },
  { code: 147, key: 'na', value: 'na', flag: 'na', text: 'Namibia' },
  { code: 148, key: 'nr', value: 'nr', flag: 'nr', text: 'Nauru' },
  { code: 149, key: 'np', value: 'np', flag: 'np', text: 'Nepal' },
  { code: 150, key: 'an', value: 'an', flag: 'an', text: 'Netherlands Antilles' },
  { code: 151, key: 'nl', value: 'nl', flag: 'nl', text: 'Netherlands' },
  { code: 152, key: 'nc', value: 'nc', flag: 'nc', text: 'New Caledonia' },
  { code: 153, key: 'pg', value: 'pg', flag: 'pg', text: 'New Guinea' },
  { code: 154, key: 'nz', value: 'nz', flag: 'nz', text: 'New Zealand' },
  { code: 155, key: 'ni', value: 'ni', flag: 'ni', text: 'Nicaragua' },
  { code: 156, key: 'ne', value: 'ne', flag: 'ne', text: 'Niger' },
  { code: 157, key: 'ng', value: 'ng', flag: 'ng', text: 'Nigeria' },
  { code: 158, key: 'nu', value: 'nu', flag: 'nu', text: 'Niue' },
  { code: 159, key: 'nf', value: 'nf', flag: 'nf', text: 'Norfolk Island' },
  { code: 160, key: 'kp', value: 'kp', flag: 'kp', text: 'North Korea' },
  { code: 161, key: 'mp', value: 'mp', flag: 'mp', text: 'Northern Mariana Islands' },
  { code: 162, key: 'no', value: 'no', flag: 'no', text: 'Norway' },
  { code: 163, key: 'om', value: 'om', flag: 'om', text: 'Oman' },
  { code: 164, key: 'pk', value: 'pk', flag: 'pk', text: 'Pakistan' },
  { code: 165, key: 'pw', value: 'pw', flag: 'pw', text: 'Palau' },
  { code: 166, key: 'ps', value: 'ps', flag: 'ps', text: 'Palestine' },
  { code: 167, key: 'pa', value: 'pa', flag: 'pa', text: 'Panama' },
  { code: 168, key: 'py', value: 'py', flag: 'py', text: 'Paraguay' },
  { code: 169, key: 'pe', value: 'pe', flag: 'pe', text: 'Peru' },
  { code: 170, key: 'ph', value: 'ph', flag: 'ph', text: 'Philippines' },
  { code: 171, key: 'pn', value: 'pn', flag: 'pn', text: 'Pitcairn Islands' },
  { code: 172, key: 'pl', value: 'pl', flag: 'pl', text: 'Poland' },
  { code: 173, key: 'pt', value: 'pt', flag: 'pt', text: 'Portugal' },
  { code: 174, key: 'pr', value: 'pr', flag: 'pr', text: 'Puerto Rico' },
  { code: 175, key: 'qa', value: 'qa', flag: 'qa', text: 'Qatar' },
  { code: 176, key: 're', value: 're', flag: 're', text: 'Reunion' },
  { code: 177, key: 'ro', value: 'ro', flag: 'ro', text: 'Romania' },
  { code: 178, key: 'ru', value: 'ru', flag: 'ru', text: 'Russia' },
  { code: 179, key: 'rw', value: 'rw', flag: 'rw', text: 'Rwanda' },
  { code: 180, key: 'sh', value: 'sh', flag: 'sh', text: 'Saint Helena' },
  { code: 181, key: 'kn', value: 'kn', flag: 'kn', text: 'Saint Kitts and Nevis' },
  { code: 182, key: 'lc', value: 'lc', flag: 'lc', text: 'Saint Lucia' },
  { code: 183, key: 'pm', value: 'pm', flag: 'pm', text: 'Saint Pierre' },
  { code: 184, key: 'vc', value: 'vc', flag: 'vc', text: 'Saint Vincent' },
  { code: 185, key: 'ws', value: 'ws', flag: 'ws', text: 'Samoa' },
  { code: 186, key: 'sm', value: 'sm', flag: 'sm', text: 'San Marino' },
  { code: 187, key: 'gs', value: 'gs', flag: 'gs', text: 'Sandwich Islands' },
  { code: 188, key: 'st', value: 'st', flag: 'st', text: 'Sao Tome' },
  { code: 189, key: 'sa', value: 'sa', flag: 'sa', text: 'Saudi Arabia' },
  { code: 190, key: 'sn', value: 'sn', flag: 'sn', text: 'Senegal' },
  { code: 191, key: 'cs', value: 'cs', flag: 'cs', text: 'Serbia' },
  { code: 192, key: 'rs', value: 'rs', flag: 'rs', text: 'Serbia' },
  { code: 193, key: 'sc', value: 'sc', flag: 'sc', text: 'Seychelles' },
  { code: 194, key: 'sl', value: 'sl', flag: 'sl', text: 'Sierra Leone' },
  { code: 195, key: 'sg', value: 'sg', flag: 'sg', text: 'Singapore' },
  { code: 196, key: 'sk', value: 'sk', flag: 'sk', text: 'Slovakia' },
  { code: 197, key: 'si', value: 'si', flag: 'si', text: 'Slovenia' },
  { code: 198, key: 'sb', value: 'sb', flag: 'sb', text: 'Solomon Islands' },
  { code: 199, key: 'so', value: 'so', flag: 'so', text: 'Somalia' },
  { code: 200, key: 'za', value: 'za', flag: 'za', text: 'South Africa' },
  { code: 201, key: 'kr', value: 'kr', flag: 'kr', text: 'South Korea' },
  { code: 202, key: 'es', value: 'es', flag: 'es', text: 'Spain' },
  { code: 203, key: 'lk', value: 'lk', flag: 'lk', text: 'Sri Lanka' },
  { code: 204, key: 'sd', value: 'sd', flag: 'sd', text: 'Sudan' },
  { code: 205, key: 'sr', value: 'sr', flag: 'sr', text: 'Suriname' },
  { code: 206, key: 'sj', value: 'sj', flag: 'sj', text: 'Svalbard' },
  { code: 207, key: 'sz', value: 'sz', flag: 'sz', text: 'Swaziland' },
  { code: 208, key: 'se', value: 'se', flag: 'se', text: 'Sweden' },
  { code: 209, key: 'ch', value: 'ch', flag: 'ch', text: 'Switzerland' },
  { code: 210, key: 'sy', value: 'sy', flag: 'sy', text: 'Syria' },
  { code: 211, key: 'tw', value: 'tw', flag: 'tw', text: 'Taiwan' },
  { code: 212, key: 'tj', value: 'tj', flag: 'tj', text: 'Tajikistan' },
  { code: 213, key: 'tz', value: 'tz', flag: 'tz', text: 'Tanzania' },
  { code: 214, key: 'th', value: 'th', flag: 'th', text: 'Thailand' },
  { code: 215, key: 'tl', value: 'tl', flag: 'tl', text: 'Timorleste' },
  { code: 216, key: 'tg', value: 'tg', flag: 'tg', text: 'Togo' },
  { code: 217, key: 'tk', value: 'tk', flag: 'tk', text: 'Tokelau' },
  { code: 218, key: 'to', value: 'to', flag: 'to', text: 'Tonga' },
  { code: 219, key: 'tt', value: 'tt', flag: 'tt', text: 'Trinidad' },
  { code: 220, key: 'tn', value: 'tn', flag: 'tn', text: 'Tunisia' },
  { code: 221, key: 'tr', value: 'tr', flag: 'tr', text: 'Turkey' },
  { code: 222, key: 'tm', value: 'tm', flag: 'tm', text: 'Turkmenistan' },
  { code: 223, key: 'tv', value: 'tv', flag: 'tv', text: 'Tuvalu' },
  { code: 224, key: 'ug', value: 'ug', flag: 'ug', text: 'Uganda' },
  { code: 225, key: 'ua', value: 'ua', flag: 'ua', text: 'Ukraine' },
  { code: 226, key: 'ae', value: 'ae', flag: 'ae', text: 'United Arab Emirates' },
  { code: 227, key: 'us', value: 'us', flag: 'us', text: 'United States' },
  { code: 228, key: 'uy', value: 'uy', flag: 'uy', text: 'Uruguay' },
  { code: 229, key: 'um', value: 'um', flag: 'um', text: 'Us Minor Islands' },
  { code: 230, key: 'vi', value: 'vi', flag: 'vi', text: 'Us Virgin Islands' },
  { code: 231, key: 'uz', value: 'uz', flag: 'uz', text: 'Uzbekistan' },
  { code: 232, key: 'vu', value: 'vu', flag: 'vu', text: 'Vanuatu' },
  { code: 233, key: 'va', value: 'va', flag: 'va', text: 'Vatican City' },
  { code: 234, key: 've', value: 've', flag: 've', text: 'Venezuela' },
  { code: 235, key: 'vn', value: 'vn', flag: 'vn', text: 'Vietnam' },
  { code: 236, key: 'wf', value: 'wf', flag: 'wf', text: 'Wallis and Futuna' },
  { code: 237, key: 'eh', value: 'eh', flag: 'eh', text: 'Western Sahara' },
  { code: 238, key: 'ye', value: 'ye', flag: 'ye', text: 'Yemen' },
  { code: 239, key: 'zm', value: 'zm', flag: 'zm', text: 'Zambia' },
  { code: 240, key: 'zw', value: 'zw', flag: 'zw', text: 'Zimbabwe' },

]

// I generated this manually from countryOptions by running the below in a console:
// countryOptions.reduce((o, val) => Object.assign(o, { [val.code]: val}), {})
export const countryOptionsDict = {
  0: { code: 0, key: 'af', value: 'af', flag: 'af', text: 'Afghanistan' },
  1: { code: 1, key: 'ax', value: 'ax', flag: 'ax', text: 'Aland Islands' },
  2: { code: 2, key: 'al', value: 'al', flag: 'al', text: 'Albania' },
  3: { code: 3, key: 'dz', value: 'dz', flag: 'dz', text: 'Algeria' },
  4: { code: 4, key: 'as', value: 'as', flag: 'as', text: 'American Samoa' },
  5: { code: 5, key: 'ad', value: 'ad', flag: 'ad', text: 'Andorra' },
  6: { code: 6, key: 'ao', value: 'ao', flag: 'ao', text: 'Angola' },
  7: { code: 7, key: 'ai', value: 'ai', flag: 'ai', text: 'Anguilla' },
  8: { code: 8, key: 'ag', value: 'ag', flag: 'ag', text: 'Antigua' },
  9: { code: 9, key: 'ar', value: 'ar', flag: 'ar', text: 'Argentina' },
  10: { code: 10, key: 'am', value: 'am', flag: 'am', text: 'Armenia' },
  11: { code: 11, key: 'aw', value: 'aw', flag: 'aw', text: 'Aruba' },
  12: { code: 12, key: 'au', value: 'au', flag: 'au', text: 'Australia' },
  13: { code: 13, key: 'at', value: 'at', flag: 'at', text: 'Austria' },
  14: { code: 14, key: 'az', value: 'az', flag: 'az', text: 'Azerbaijan' },
  15: { code: 15, key: 'bs', value: 'bs', flag: 'bs', text: 'Bahamas' },
  16: { code: 16, key: 'bh', value: 'bh', flag: 'bh', text: 'Bahrain' },
  17: { code: 17, key: 'bd', value: 'bd', flag: 'bd', text: 'Bangladesh' },
  18: { code: 18, key: 'bb', value: 'bb', flag: 'bb', text: 'Barbados' },
  19: { code: 19, key: 'by', value: 'by', flag: 'by', text: 'Belarus' },
  20: { code: 20, key: 'be', value: 'be', flag: 'be', text: 'Belgium' },
  21: { code: 21, key: 'bz', value: 'bz', flag: 'bz', text: 'Belize' },
  22: { code: 22, key: 'bj', value: 'bj', flag: 'bj', text: 'Benin' },
  23: { code: 23, key: 'bm', value: 'bm', flag: 'bm', text: 'Bermuda' },
  24: { code: 24, key: 'bt', value: 'bt', flag: 'bt', text: 'Bhutan' },
  25: { code: 25, key: 'bo', value: 'bo', flag: 'bo', text: 'Bolivia' },
  26: { code: 26, key: 'ba', value: 'ba', flag: 'ba', text: 'Bosnia' },
  27: { code: 27, key: 'bw', value: 'bw', flag: 'bw', text: 'Botswana' },
  28: { code: 28, key: 'bv', value: 'bv', flag: 'bv', text: 'Bouvet Island' },
  29: { code: 29, key: 'br', value: 'br', flag: 'br', text: 'Brazil' },
  30: { code: 30, key: 'vg', value: 'vg', flag: 'vg', text: 'British Virgin Islands' },
  31: { code: 31, key: 'bn', value: 'bn', flag: 'bn', text: 'Brunei' },
  32: { code: 32, key: 'bg', value: 'bg', flag: 'bg', text: 'Bulgaria' },
  33: { code: 33, key: 'bf', value: 'bf', flag: 'bf', text: 'Burkina Faso' },
  34: { code: 34, key: 'bi', value: 'bi', flag: 'bi', text: 'Burundi' },
  35: { code: 35, key: 'tc', value: 'tc', flag: 'tc', text: 'Caicos Islands' },
  36: { code: 36, key: 'kh', value: 'kh', flag: 'kh', text: 'Cambodia' },
  37: { code: 37, key: 'cm', value: 'cm', flag: 'cm', text: 'Cameroon' },
  38: { code: 38, key: 'ca', value: 'ca', flag: 'ca', text: 'Canada' },
  39: { code: 39, key: 'cv', value: 'cv', flag: 'cv', text: 'Cape Verde' },
  40: { code: 40, key: 'ky', value: 'ky', flag: 'ky', text: 'Cayman Islands' },
  41: { code: 41, key: 'cf', value: 'cf', flag: 'cf', text: 'Central African Republic' },
  42: { code: 42, key: 'td', value: 'td', flag: 'td', text: 'Chad' },
  43: { code: 43, key: 'cl', value: 'cl', flag: 'cl', text: 'Chile' },
  44: { code: 44, key: 'cn', value: 'cn', flag: 'cn', text: 'China' },
  45: { code: 45, key: 'cx', value: 'cx', flag: 'cx', text: 'Christmas Island' },
  46: { code: 46, key: 'cc', value: 'cc', flag: 'cc', text: 'Cocos Islands' },
  47: { code: 47, key: 'co', value: 'co', flag: 'co', text: 'Colombia' },
  48: { code: 48, key: 'km', value: 'km', flag: 'km', text: 'Comoros' },
  49: { code: 49, key: 'cg', value: 'cg', flag: 'cg', text: 'Congo Brazzaville' },
  50: { code: 50, key: 'cd', value: 'cd', flag: 'cd', text: 'Congo' },
  51: { code: 51, key: 'ck', value: 'ck', flag: 'ck', text: 'Cook Islands' },
  52: { code: 52, key: 'cr', value: 'cr', flag: 'cr', text: 'Costa Rica' },
  53: { code: 53, key: 'ci', value: 'ci', flag: 'ci', text: 'Cote Divoire' },
  54: { code: 54, key: 'hr', value: 'hr', flag: 'hr', text: 'Croatia' },
  55: { code: 55, key: 'cu', value: 'cu', flag: 'cu', text: 'Cuba' },
  56: { code: 56, key: 'cy', value: 'cy', flag: 'cy', text: 'Cyprus' },
  57: { code: 57, key: 'cz', value: 'cz', flag: 'cz', text: 'Czech Republic' },
  58: { code: 58, key: 'dk', value: 'dk', flag: 'dk', text: 'Denmark' },
  59: { code: 59, key: 'dj', value: 'dj', flag: 'dj', text: 'Djibouti' },
  60: { code: 60, key: 'dm', value: 'dm', flag: 'dm', text: 'Dominica' },
  61: { code: 61, key: 'do', value: 'do', flag: 'do', text: 'Dominican Republic' },
  62: { code: 62, key: 'ec', value: 'ec', flag: 'ec', text: 'Ecuador' },
  63: { code: 63, key: 'eg', value: 'eg', flag: 'eg', text: 'Egypt' },
  64: { code: 64, key: 'sv', value: 'sv', flag: 'sv', text: 'El Salvador' },
  65: { code: 65, key: 'gb', value: 'gb', flag: 'gb', text: 'England' },
  66: { code: 66, key: 'gq', value: 'gq', flag: 'gq', text: 'Equatorial Guinea' },
  67: { code: 67, key: 'er', value: 'er', flag: 'er', text: 'Eritrea' },
  68: { code: 68, key: 'ee', value: 'ee', flag: 'ee', text: 'Estonia' },
  69: { code: 69, key: 'et', value: 'et', flag: 'et', text: 'Ethiopia' },
  70: { code: 70, key: 'eu', value: 'eu', flag: 'eu', text: 'European Union' },
  71: { code: 71, key: 'fk', value: 'fk', flag: 'fk', text: 'Falkland Islands' },
  72: { code: 72, key: 'fo', value: 'fo', flag: 'fo', text: 'Faroe Islands' },
  73: { code: 73, key: 'fj', value: 'fj', flag: 'fj', text: 'Fiji' },
  74: { code: 74, key: 'fi', value: 'fi', flag: 'fi', text: 'Finland' },
  75: { code: 75, key: 'fr', value: 'fr', flag: 'fr', text: 'France' },
  76: { code: 76, key: 'gf', value: 'gf', flag: 'gf', text: 'French Guiana' },
  77: { code: 77, key: 'pf', value: 'pf', flag: 'pf', text: 'French Polynesia' },
  78: { code: 78, key: 'tf', value: 'tf', flag: 'tf', text: 'French Territories' },
  79: { code: 79, key: 'ga', value: 'ga', flag: 'ga', text: 'Gabon' },
  80: { code: 80, key: 'gm', value: 'gm', flag: 'gm', text: 'Gambia' },
  81: { code: 81, key: 'ge', value: 'ge', flag: 'ge', text: 'Georgia' },
  82: { code: 82, key: 'de', value: 'de', flag: 'de', text: 'Germany' },
  83: { code: 83, key: 'gh', value: 'gh', flag: 'gh', text: 'Ghana' },
  84: { code: 84, key: 'gi', value: 'gi', flag: 'gi', text: 'Gibraltar' },
  85: { code: 85, key: 'gr', value: 'gr', flag: 'gr', text: 'Greece' },
  86: { code: 86, key: 'gl', value: 'gl', flag: 'gl', text: 'Greenland' },
  87: { code: 87, key: 'gd', value: 'gd', flag: 'gd', text: 'Grenada' },
  88: { code: 88, key: 'gp', value: 'gp', flag: 'gp', text: 'Guadeloupe' },
  89: { code: 89, key: 'gu', value: 'gu', flag: 'gu', text: 'Guam' },
  90: { code: 90, key: 'gt', value: 'gt', flag: 'gt', text: 'Guatemala' },
  91: { code: 91, key: 'gw', value: 'gw', flag: 'gw', text: 'Guinea-Bissau' },
  92: { code: 92, key: 'gn', value: 'gn', flag: 'gn', text: 'Guinea' },
  93: { code: 93, key: 'gy', value: 'gy', flag: 'gy', text: 'Guyana' },
  94: { code: 94, key: 'ht', value: 'ht', flag: 'ht', text: 'Haiti' },
  95: { code: 95, key: 'hm', value: 'hm', flag: 'hm', text: 'Heard Island' },
  96: { code: 96, key: 'hn', value: 'hn', flag: 'hn', text: 'Honduras' },
  97: { code: 97, key: 'hk', value: 'hk', flag: 'hk', text: 'Hong Kong' },
  98: { code: 98, key: 'hu', value: 'hu', flag: 'hu', text: 'Hungary' },
  99: { code: 99, key: 'is', value: 'is', flag: 'is', text: 'Iceland' },
  100: { code: 100, key: 'in', value: 'in', flag: 'in', text: 'India' },
  101: { code: 101, key: 'io', value: 'io', flag: 'io', text: 'Indian Ocean Territory' },
  102: { code: 102, key: 'id', value: 'id', flag: 'id', text: 'Indonesia' },
  103: { code: 103, key: 'ir', value: 'ir', flag: 'ir', text: 'Iran' },
  104: { code: 104, key: 'iq', value: 'iq', flag: 'iq', text: 'Iraq' },
  105: { code: 105, key: 'ie', value: 'ie', flag: 'ie', text: 'Ireland' },
  106: { code: 106, key: 'il', value: 'il', flag: 'il', text: 'Israel' },
  107: { code: 107, key: 'it', value: 'it', flag: 'it', text: 'Italy' },
  108: { code: 108, key: 'jm', value: 'jm', flag: 'jm', text: 'Jamaica' },
  109: { code: 109, key: 'jp', value: 'jp', flag: 'jp', text: 'Japan' },
  110: { code: 110, key: 'jo', value: 'jo', flag: 'jo', text: 'Jordan' },
  111: { code: 111, key: 'kz', value: 'kz', flag: 'kz', text: 'Kazakhstan' },
  112: { code: 112, key: 'ke', value: 'ke', flag: 'ke', text: 'Kenya' },
  113: { code: 113, key: 'ki', value: 'ki', flag: 'ki', text: 'Kiribati' },
  114: { code: 114, key: 'kw', value: 'kw', flag: 'kw', text: 'Kuwait' },
  115: { code: 115, key: 'kg', value: 'kg', flag: 'kg', text: 'Kyrgyzstan' },
  116: { code: 116, key: 'la', value: 'la', flag: 'la', text: 'Laos' },
  117: { code: 117, key: 'lv', value: 'lv', flag: 'lv', text: 'Latvia' },
  118: { code: 118, key: 'lb', value: 'lb', flag: 'lb', text: 'Lebanon' },
  119: { code: 119, key: 'ls', value: 'ls', flag: 'ls', text: 'Lesotho' },
  120: { code: 120, key: 'lr', value: 'lr', flag: 'lr', text: 'Liberia' },
  121: { code: 121, key: 'ly', value: 'ly', flag: 'ly', text: 'Libya' },
  122: { code: 122, key: 'li', value: 'li', flag: 'li', text: 'Liechtenstein' },
  123: { code: 123, key: 'lt', value: 'lt', flag: 'lt', text: 'Lithuania' },
  124: { code: 124, key: 'lu', value: 'lu', flag: 'lu', text: 'Luxembourg' },
  125: { code: 125, key: 'mo', value: 'mo', flag: 'mo', text: 'Macau' },
  126: { code: 126, key: 'mk', value: 'mk', flag: 'mk', text: 'Macedonia' },
  127: { code: 127, key: 'mg', value: 'mg', flag: 'mg', text: 'Madagascar' },
  128: { code: 128, key: 'mw', value: 'mw', flag: 'mw', text: 'Malawi' },
  129: { code: 129, key: 'my', value: 'my', flag: 'my', text: 'Malaysia' },
  130: { code: 130, key: 'mv', value: 'mv', flag: 'mv', text: 'Maldives' },
  131: { code: 131, key: 'ml', value: 'ml', flag: 'ml', text: 'Mali' },
  132: { code: 132, key: 'mt', value: 'mt', flag: 'mt', text: 'Malta' },
  133: { code: 133, key: 'mh', value: 'mh', flag: 'mh', text: 'Marshall Islands' },
  134: { code: 134, key: 'mq', value: 'mq', flag: 'mq', text: 'Martinique' },
  135: { code: 135, key: 'mr', value: 'mr', flag: 'mr', text: 'Mauritania' },
  136: { code: 136, key: 'mu', value: 'mu', flag: 'mu', text: 'Mauritius' },
  137: { code: 137, key: 'yt', value: 'yt', flag: 'yt', text: 'Mayotte' },
  138: { code: 138, key: 'mx', value: 'mx', flag: 'mx', text: 'Mexico' },
  139: { code: 139, key: 'fm', value: 'fm', flag: 'fm', text: 'Micronesia' },
  140: { code: 140, key: 'md', value: 'md', flag: 'md', text: 'Moldova' },
  141: { code: 141, key: 'mc', value: 'mc', flag: 'mc', text: 'Monaco' },
  142: { code: 142, key: 'mn', value: 'mn', flag: 'mn', text: 'Mongolia' },
  143: { code: 143, key: 'me', value: 'me', flag: 'me', text: 'Montenegro' },
  144: { code: 144, key: 'ms', value: 'ms', flag: 'ms', text: 'Montserrat' },
  145: { code: 145, key: 'ma', value: 'ma', flag: 'ma', text: 'Morocco' },
  146: { code: 146, key: 'mz', value: 'mz', flag: 'mz', text: 'Mozambique' },
  147: { code: 147, key: 'na', value: 'na', flag: 'na', text: 'Namibia' },
  148: { code: 148, key: 'nr', value: 'nr', flag: 'nr', text: 'Nauru' },
  149: { code: 149, key: 'np', value: 'np', flag: 'np', text: 'Nepal' },
  150: { code: 150, key: 'an', value: 'an', flag: 'an', text: 'Netherlands Antilles' },
  151: { code: 151, key: 'nl', value: 'nl', flag: 'nl', text: 'Netherlands' },
  152: { code: 152, key: 'nc', value: 'nc', flag: 'nc', text: 'New Caledonia' },
  153: { code: 153, key: 'pg', value: 'pg', flag: 'pg', text: 'New Guinea' },
  154: { code: 154, key: 'nz', value: 'nz', flag: 'nz', text: 'New Zealand' },
  155: { code: 155, key: 'ni', value: 'ni', flag: 'ni', text: 'Nicaragua' },
  156: { code: 156, key: 'ne', value: 'ne', flag: 'ne', text: 'Niger' },
  157: { code: 157, key: 'ng', value: 'ng', flag: 'ng', text: 'Nigeria' },
  158: { code: 158, key: 'nu', value: 'nu', flag: 'nu', text: 'Niue' },
  159: { code: 159, key: 'nf', value: 'nf', flag: 'nf', text: 'Norfolk Island' },
  160: { code: 160, key: 'kp', value: 'kp', flag: 'kp', text: 'North Korea' },
  161: { code: 161, key: 'mp', value: 'mp', flag: 'mp', text: 'Northern Mariana Islands' },
  162: { code: 162, key: 'no', value: 'no', flag: 'no', text: 'Norway' },
  163: { code: 163, key: 'om', value: 'om', flag: 'om', text: 'Oman' },
  164: { code: 164, key: 'pk', value: 'pk', flag: 'pk', text: 'Pakistan' },
  165: { code: 165, key: 'pw', value: 'pw', flag: 'pw', text: 'Palau' },
  166: { code: 166, key: 'ps', value: 'ps', flag: 'ps', text: 'Palestine' },
  167: { code: 167, key: 'pa', value: 'pa', flag: 'pa', text: 'Panama' },
  168: { code: 168, key: 'py', value: 'py', flag: 'py', text: 'Paraguay' },
  169: { code: 169, key: 'pe', value: 'pe', flag: 'pe', text: 'Peru' },
  170: { code: 170, key: 'ph', value: 'ph', flag: 'ph', text: 'Philippines' },
  171: { code: 171, key: 'pn', value: 'pn', flag: 'pn', text: 'Pitcairn Islands' },
  172: { code: 172, key: 'pl', value: 'pl', flag: 'pl', text: 'Poland' },
  173: { code: 173, key: 'pt', value: 'pt', flag: 'pt', text: 'Portugal' },
  174: { code: 174, key: 'pr', value: 'pr', flag: 'pr', text: 'Puerto Rico' },
  175: { code: 175, key: 'qa', value: 'qa', flag: 'qa', text: 'Qatar' },
  176: { code: 176, key: 're', value: 're', flag: 're', text: 'Reunion' },
  177: { code: 177, key: 'ro', value: 'ro', flag: 'ro', text: 'Romania' },
  178: { code: 178, key: 'ru', value: 'ru', flag: 'ru', text: 'Russia' },
  179: { code: 179, key: 'rw', value: 'rw', flag: 'rw', text: 'Rwanda' },
  180: { code: 180, key: 'sh', value: 'sh', flag: 'sh', text: 'Saint Helena' },
  181: { code: 181, key: 'kn', value: 'kn', flag: 'kn', text: 'Saint Kitts and Nevis' },
  182: { code: 182, key: 'lc', value: 'lc', flag: 'lc', text: 'Saint Lucia' },
  183: { code: 183, key: 'pm', value: 'pm', flag: 'pm', text: 'Saint Pierre' },
  184: { code: 184, key: 'vc', value: 'vc', flag: 'vc', text: 'Saint Vincent' },
  185: { code: 185, key: 'ws', value: 'ws', flag: 'ws', text: 'Samoa' },
  186: { code: 186, key: 'sm', value: 'sm', flag: 'sm', text: 'San Marino' },
  187: { code: 187, key: 'gs', value: 'gs', flag: 'gs', text: 'Sandwich Islands' },
  188: { code: 188, key: 'st', value: 'st', flag: 'st', text: 'Sao Tome' },
  189: { code: 189, key: 'sa', value: 'sa', flag: 'sa', text: 'Saudi Arabia' },
  190: { code: 190, key: 'sn', value: 'sn', flag: 'sn', text: 'Senegal' },
  191: { code: 191, key: 'cs', value: 'cs', flag: 'cs', text: 'Serbia' },
  192: { code: 192, key: 'rs', value: 'rs', flag: 'rs', text: 'Serbia' },
  193: { code: 193, key: 'sc', value: 'sc', flag: 'sc', text: 'Seychelles' },
  194: { code: 194, key: 'sl', value: 'sl', flag: 'sl', text: 'Sierra Leone' },
  195: { code: 195, key: 'sg', value: 'sg', flag: 'sg', text: 'Singapore' },
  196: { code: 196, key: 'sk', value: 'sk', flag: 'sk', text: 'Slovakia' },
  197: { code: 197, key: 'si', value: 'si', flag: 'si', text: 'Slovenia' },
  198: { code: 198, key: 'sb', value: 'sb', flag: 'sb', text: 'Solomon Islands' },
  199: { code: 199, key: 'so', value: 'so', flag: 'so', text: 'Somalia' },
  200: { code: 200, key: 'za', value: 'za', flag: 'za', text: 'South Africa' },
  201: { code: 201, key: 'kr', value: 'kr', flag: 'kr', text: 'South Korea' },
  202: { code: 202, key: 'es', value: 'es', flag: 'es', text: 'Spain' },
  203: { code: 203, key: 'lk', value: 'lk', flag: 'lk', text: 'Sri Lanka' },
  204: { code: 204, key: 'sd', value: 'sd', flag: 'sd', text: 'Sudan' },
  205: { code: 205, key: 'sr', value: 'sr', flag: 'sr', text: 'Suriname' },
  206: { code: 206, key: 'sj', value: 'sj', flag: 'sj', text: 'Svalbard' },
  207: { code: 207, key: 'sz', value: 'sz', flag: 'sz', text: 'Swaziland' },
  208: { code: 208, key: 'se', value: 'se', flag: 'se', text: 'Sweden' },
  209: { code: 209, key: 'ch', value: 'ch', flag: 'ch', text: 'Switzerland' },
  210: { code: 210, key: 'sy', value: 'sy', flag: 'sy', text: 'Syria' },
  211: { code: 211, key: 'tw', value: 'tw', flag: 'tw', text: 'Taiwan' },
  212: { code: 212, key: 'tj', value: 'tj', flag: 'tj', text: 'Tajikistan' },
  213: { code: 213, key: 'tz', value: 'tz', flag: 'tz', text: 'Tanzania' },
  214: { code: 214, key: 'th', value: 'th', flag: 'th', text: 'Thailand' },
  215: { code: 215, key: 'tl', value: 'tl', flag: 'tl', text: 'Timorleste' },
  216: { code: 216, key: 'tg', value: 'tg', flag: 'tg', text: 'Togo' },
  217: { code: 217, key: 'tk', value: 'tk', flag: 'tk', text: 'Tokelau' },
  218: { code: 218, key: 'to', value: 'to', flag: 'to', text: 'Tonga' },
  219: { code: 219, key: 'tt', value: 'tt', flag: 'tt', text: 'Trinidad' },
  220: { code: 220, key: 'tn', value: 'tn', flag: 'tn', text: 'Tunisia' },
  221: { code: 221, key: 'tr', value: 'tr', flag: 'tr', text: 'Turkey' },
  222: { code: 222, key: 'tm', value: 'tm', flag: 'tm', text: 'Turkmenistan' },
  223: { code: 223, key: 'tv', value: 'tv', flag: 'tv', text: 'Tuvalu' },
  224: { code: 224, key: 'ug', value: 'ug', flag: 'ug', text: 'Uganda' },
  225: { code: 225, key: 'ua', value: 'ua', flag: 'ua', text: 'Ukraine' },
  226: { code: 226, key: 'ae', value: 'ae', flag: 'ae', text: 'United Arab Emirates' },
  227: { code: 227, key: 'us', value: 'us', flag: 'us', text: 'United States' },
  228: { code: 228, key: 'uy', value: 'uy', flag: 'uy', text: 'Uruguay' },
  229: { code: 229, key: 'um', value: 'um', flag: 'um', text: 'Us Minor Islands' },
  230: { code: 230, key: 'vi', value: 'vi', flag: 'vi', text: 'Us Virgin Islands' },
  231: { code: 231, key: 'uz', value: 'uz', flag: 'uz', text: 'Uzbekistan' },
  232: { code: 232, key: 'vu', value: 'vu', flag: 'vu', text: 'Vanuatu' },
  233: { code: 233, key: 'va', value: 'va', flag: 'va', text: 'Vatican City' },
  234: { code: 234, key: 've', value: 've', flag: 've', text: 'Venezuela' },
  235: { code: 235, key: 'vn', value: 'vn', flag: 'vn', text: 'Vietnam' },
  236: { code: 236, key: 'wf', value: 'wf', flag: 'wf', text: 'Wallis and Futuna' },
  237: { code: 237, key: 'eh', value: 'eh', flag: 'eh', text: 'Western Sahara' },
  238: { code: 238, key: 'ye', value: 'ye', flag: 'ye', text: 'Yemen' },
  239: { code: 239, key: 'zm', value: 'zm', flag: 'zm', text: 'Zambia' },
  240: { code: 240, key: 'zw', value: 'zw', flag: 'zw', text: 'Zimbabwe' },
}

export const languageOptions = [
  { key: 'Arabic', text: 'Arabic', value: 'Arabic' },
  { key: 'Chinese', text: 'Chinese', value: 'Chinese' },
  { key: 'Danish', text: 'Danish', value: 'Danish' },
  { key: 'Dutch', text: 'Dutch', value: 'Dutch' },
  { key: 'English', text: 'English', value: 'English' },
  { key: 'French', text: 'French', value: 'French' },
  { key: 'German', text: 'German', value: 'German' },
  { key: 'Greek', text: 'Greek', value: 'Greek' },
  { key: 'Hungarian', text: 'Hungarian', value: 'Hungarian' },
  { key: 'Italian', text: 'Italian', value: 'Italian' },
  { key: 'Japanese', text: 'Japanese', value: 'Japanese' },
  { key: 'Korean', text: 'Korean', value: 'Korean' },
  { key: 'Lithuanian', text: 'Lithuanian', value: 'Lithuanian' },
  { key: 'Persian', text: 'Persian', value: 'Persian' },
  { key: 'Polish', text: 'Polish', value: 'Polish' },
  { key: 'Portuguese', text: 'Portuguese', value: 'Portuguese' },
  { key: 'Russian', text: 'Russian', value: 'Russian' },
  { key: 'Spanish', text: 'Spanish', value: 'Spanish' },
  { key: 'Swedish', text: 'Swedish', value: 'Swedish' },
  { key: 'Turkish', text: 'Turkish', value: 'Turkish' },
  { key: 'Vietnamese', text: 'Vietnamese', value: 'Vietnamese' },
]

export const tagOptions = [
  {
    key: 'Important',
    text: 'Important',
    value: 'Important',
    label: { color: 'red', empty: true, circular: true },
  },
  {
    key: 'Announcement',
    text: 'Announcement',
    value: 'Announcement',
    label: { color: 'blue', empty: true, circular: true },
  },
  {
    key: 'Cannot Fix',
    text: 'Cannot Fix',
    value: 'Cannot Fix',
    label: { color: 'black', empty: true, circular: true },
  },
  {
    key: 'News',
    text: 'News',
    value: 'News',
    label: { color: 'purple', empty: true, circular: true },
  },
  {
    key: 'Enhancement',
    text: 'Enhancement',
    value: 'Enhancement',
    label: { color: 'orange', empty: true, circular: true },
  },
  {
    key: 'Change Declined',
    text: 'Change Declined',
    value: 'Change Declined',
    label: { empty: true, circular: true },
  },
  {
    key: 'Off Topic',
    text: 'Off Topic',
    value: 'Off Topic',
    label: { color: 'yellow', empty: true, circular: true },
  },
  {
    key: 'Interesting',
    text: 'Interesting',
    value: 'Interesting',
    label: { color: 'pink', empty: true, circular: true },
  },
  {
    key: 'Discussion',
    text: 'Discussion',
    value: 'Discussion',
    label: { color: 'green', empty: true, circular: true },
  },
]

export const getObjFromCountryCode = countryCode => countryOptionsDict[countryCode]

export const getOptions = (number, prefix = 'Choice ') => _.times(number, index => ({
  key: index,
  text: `${prefix}${index}`,
  value: index,
}))
